### ISSUE TITLE
Game Difficulty - Easy / Normal / Hard

### ISSUE THREAD

**Issue by IcemarkUK** [ChilliHugger/The-Lords-Of-Midnight#114]
The difficulty mode is not fully operational yet. 

1. Turn on the simplest feature which is the number of available undos. ✅

Internal this is already set to 
- Normal = 0
- Easy = 1
- Medium = 2
- Hard = 3

The numbers may need to adjusted.

2. Make random seed saved with the save game making immediate actions perform the same. ✅

**Comment by gituzzer** [comment]
Great stuff. It will be hard enough.

Suggestion: increase also the falling rate of Invigorated/tired, bold/afraid, + effect on + distance to Moon ring.

I remember (probably my mind playing games) Lords with low self-esteem or cowards turning over to the evil side, or going neutral. Must be a DDR thing...

**Comment by IcemarkUK** [comment]
> I remember (probably my mind playing games) Lords with low self-esteem or cowards turning over to the evil side, or going neutral. Must be a DDR thing...

It was a DDR thing. The manual mention that Utarg could change sides - but he couldn't :)
