### ISSUE TITLE
DDR Describe Stronghold

### ISSUE THREAD

**Issue by FrozenEmpire** [ChilliHugger/The-Lords-Of-Midnight#224]
Hi Chris,

Potential bug with DDR stronghold descriptions?

https://github.com/ChilliHugger/The-Lords-Of-Midnight/blob/10b0406554eec5bca350b08dde6f488aae2b0553/main/midnight/src/tme/scenarios/ddr/ddr_processor_text.cpp#L208

The code above only changes to SS_DESCRIPTION1 when the stronghold owners race is RA_MOONPRINCE.
In all other cases its SS_DESCRIPTION2
This means the description would not reflect anyone that has taken occupation of the stronghold as the string descriptions in the function header would indicate
//73  SS_STRONGHOLD1    The %s is occupied by armies loyal to %s.§   <<======
//74  SS_STRONGHOLD2    The %s is owned by %s who is loyal to.§
//75  SS_STRONGHOLD3    %s holds %s %s %s.§

Note the database has different strings in as well, they are:
//73	 SS_STRONGHOLD1	The %s is owned by {char:longname}.
//74  SS_STRONGHOLD2	The %s is owned by {char:longname}{char:text:loyalty}.
//75  SS_STRONGHOLD3	%s holds %s %s %s. They are %s.

Not quite sure which combination is correct...

Regards,
Andrew

**Comment by IcemarkUK** [comment]
Ok, looking in to it... but currently I think I have a bigger problem than that... :)

<img width="2272" alt="Screenshot 2024-02-04 at 17 59 42" src="https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/8301416/7f767470-c079-4d7a-bfe5-2c5f7ca19937">

**Comment by FrozenEmpire** [comment]
Oops :)

**Comment by IcemarkUK** [comment]
Ok. That was a bad clash in c++ generics! I moved some of the collections to c++ templated collections rather than my previously hand cranked collections. And Type() which is both on **stronghold** and its parent class **mxentity** -  was being taken from stronghold, whereas before it would have previously been mxentity. So the text functions were expecting a stronghold but getting something completely different!!

Anyway, to your actual question - I think I just forgot to finish this code!! I'm actually not sure why there is an overridden DDR version as the LoM/default was/is essentially correct. Although the strings would be wrong in DDR.

The description from the header is correct. SS_STRONGHOLD1 should reference the occupier. So the Moonprince check should actually be.

```
        if ( stronghold->Occupier() && stronghold->Occupier() != stronghold->Owner() ) { 
            message = SS_STRONGHOLD1 ;
            character=stronghold->Occupier();
        }
```

Which for me, I think, essentially means - delete the DDR version of this function and fix SS_STRONGHOLD1

**Comment by FrozenEmpire** [comment]
Looks like the solution to me. Thanks for checking and confirming.

**Comment by IcemarkUK** [comment]
Actually, I can see where I went wrong... the logic is the wrong way around. In LoM there was no concept of an occupier because it can only be FREE (Luxor) or the ENEMY (Doomdark). I probably just updated the wrong class and strings. The owner / occupier concept was an addition anyway.

**Comment by IcemarkUK** [comment]
The top of the functions are slightly different. I would be inclined to look at the original to decide how you actually want the descriptions to work.
<img width="1413" alt="Screenshot 2024-02-04 at 20 47 01" src="https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/8301416/43ab2096-2fb9-4913-8f9a-3b52d24f4b10">
<img width="1413" alt="Screenshot 2024-02-04 at 20 48 40" src="https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/8301416/a5a448ee-e695-4dba-912f-e05d23be564b">
<img width="1413" alt="Screenshot 2024-02-04 at 20 49 39" src="https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/8301416/2c2e73c3-8167-4c9c-8bef-d39cb4835dc4">

**Comment by IcemarkUK** [comment]
I will check the original code... just to make sure of the logic.

**Comment by IcemarkUK** [comment]
Ok. The original DDR just has the concept of owner. As in the above message. Owner will change when the stronghold is defeated. I was just trying to be clever and show the difference between owner and occupier.

**Comment by IcemarkUK** [comment]
@FrozenEmpire Scratch all that the code is right! Lemme explain.

Originally I was going to have an occupier/owner concept, it seems that is the part that I didn't finish. Or I decided to leave it like the original. So when an army changes side I actually set the owner and the occupier.

https://github.com/ChilliHugger/The-Lords-Of-Midnight/blob/10b0406554eec5bca350b08dde6f488aae2b0553/main/midnight/src/tme/scenarios/ddr/ddr_stronghold.cpp#L30-L40

So what we get is

> The [stronghold] is owned by [lord] who is loyal to the [race].

//74 SS_STRONGHOLD2 The %s is owned by {char:longname}{char:text:loyalty}.

However I don't want it to say
> The [stronghold] is owned by Luxor the Moonprince who is loyal to the Moonprince.

So instead it says
> The [stronghold] is owned by Luxor the Moonprince.

//73 SS_STRONGHOLD1 The %s is owned by {char:longname}.

And it never mentions occupier.

**Comment by FrozenEmpire** [comment]
Oh ! Wasn't expecting that twist :)

I didn't realise Owner and Occupier were always the same in DDR. I'll adjust to match in that case.

Thanks again for checking it out.

**Comment by IcemarkUK** [comment]
Yes. I broke the rules of not adding code that you don't need. Should never have added the occupier variable until I actually was ready to apply it properly!
