### ISSUE TITLE
Recruiting a Lord ends the day

### ISSUE THREAD

**Issue by derfsss** [ChilliHugger/The-Lords-Of-Midnight#243]
DDR v2.0.8 (50) Windows

Successfully recruiting someone results in the day ending for both characters, losing any extra hours left in the day and essentially ending that characters turn.

Example - Luxor goes south west to recruit Torinarg 
![1](https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/45050602/380ec4cd-f5c7-48a5-af33-db1ba04df487)

Recruitment successful but ...
![2](https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/45050602/b9723265-a48d-4943-b3d4-2e50976b0df6)

Its now night!
![3](https://github.com/ChilliHugger/The-Lords-Of-Midnight/assets/45050602/32378bfa-04c8-47c9-becb-e11b8c20a877)

**Comment by IcemarkUK** [comment]
What game options did you play with? What difficulty mode. This behaviour has changed depending on difficulty mode. Normal should leave it the same as the original. But other modes will will reduce or increase time take.

**Comment by derfsss** [comment]
You are correct it was linked to difficulty. I can only assume I had changed the difficulty by accident as it was a fresh install so good old user error!

**Comment by IcemarkUK** [comment]
> You are correct it was linked to difficulty. I can only assume I had changed the difficulty by accident as it was a fresh install so good old user error!

Np. Thanks. But maybe I need to make sure difficulty is always set correctly...
