### ISSUE TITLE
Some iPhone feedback

### ISSUE THREAD

**Issue by neils56** [ChilliHugger/The-Lords-Of-Midnight#59]
All on iPhone version

Undo doesn’t work if you switch characters before pressing it. This means for example if killed by wolves, can’t undo this event. 

Can’t see compass function at all

I think it used to be that if you moved onto a space with a new lord, the approach option came up right away. Now the think screen comes up and you have to switch to the choose screen. 

The battle report page is glitching. In an ongoing battle it reports that Doomdark’s forces are no warriors and no riders and reports them to be ahead of the character, not on same location. 
If character moves forward and then looks back, the numbers for Doomdark’s forces are correctly reported. 

On the select lords page there is a badge with ... on it. Pressing it instant quits the game and it has to be reloaded. Is that deliberate?

Otherwise, played through to the end and all seemed to work ok. 

Good job.

**Comment by IcemarkUK** [comment]
@neils56 I'm going to split this in to a couple of issues. Be grateful if you could check them over and respond to any questions if required.

**Comment by IcemarkUK** [comment]
> Can’t see compass function at all

Known issue - waiting to add it back.

> 
> I think it used to be that if you moved onto a space with a new lord, the approach option came up right away. Now the think screen comes up and you have to switch to the choose screen.

Fixed waiting release.

> The battle report page is glitching. In an ongoing battle it reports that Doomdark’s forces are no warriors and no riders and reports them to be ahead of the character, not on same location.
> If character moves forward and then looks back, the numbers for Doomdark’s forces are correctly reported.

Will investigate.

> 
> On the select lords page there is a badge with ... on it. Pressing it instant quits the game and it has to be reloaded. Is that deliberate?

Just added a fix.
