### ISSUE TITLE
Crash when choosing not to end the day

### ISSUE THREAD

**Issue by notverygeordie** [ChilliHugger/The-Lords-Of-Midnight#70]
IOS version 14.2
IPad Pro 12.9” 3rd Gen
Select “Night” and then select “No” at the “Are you sure you are ready to end the day” prompt.
App is terminated with extreme prejudice

**Comment by notverygeordie** [comment]
Same on iOS version 14.2 on iPhone 7
TestFlight has sent in a report with that test, so hopefully that can be tallied up with this report.

**Comment by IcemarkUK** [comment]
@notverygeordie Every time with this save game? Or every time?

**Comment by notverygeordie** [comment]
Every time (on both devices). Started another new game on each and found the same.
