### ISSUE TITLE
Crash when choosing not to read Playing Guide

### ISSUE THREAD

**Issue by notverygeordie** [ChilliHugger/The-Lords-Of-Midnight#71]
iOS 14.2 on iPhone 7 and iPadPro 12.9” 3rd Gen

Selected “?” on book icon in the bottom right hand corner of the start menu. Respond “No” to the dialog “You are about to open a browser window to read the Lords of Midnight Playing Guide. Are you sure that you wish to continue?”

**Comment by IcemarkUK** [comment]
> iOS 14.2 on iPhone 7 and iPadPro 12.9” 3rd Gen
> 
> Selected “?” on book icon in the bottom right hand corner of the start menu. Respond “No” to the dialog “You are about to open a browser window to read the Lords of Midnight Playing Guide. Are you sure that you wish to continue?”

Does this happen every time?

**Comment by notverygeordie** [comment]
Yes, on both devices. I’ve just tried killing the app by swiping up and it still happened. Then turned the phone off and on again and it also still happened. With luck you have a TestFlight report to match - I can generate another if needed. About to make sure I’m updated to the version you just released.

**Comment by notverygeordie** [comment]
Same problem on the Novella. Looks a bit like AreYouSure() with null third parameter is blowing up. Testing my way through them, I have found that they all crash (except the display mode one which isn’t reachable code on the iOS versions). I guess that makes this and #70 equivalent.

**Comment by IcemarkUK** [comment]
Yes. Not looked at it but the no was a new optional. I suspect I missed off the null check. 

Chris
